In [23]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [24]:
X, Y = make_regression(n_samples=1000, n_features= 2, n_informative=2, n_targets=1, noise =50)

In [25]:
df = pd.DataFrame({'Feature 1':X[:,0], 'Feature 2':X[:,1], 'Target':Y})

In [26]:
df.head()

   Feature 1  Feature 2     Target
0   0.498499   0.264261 -23.470599
1  -0.259446   1.372130   7.376257
2  -1.187250   0.049829 -14.763565
3   0.412411  -1.035217 -90.564984
4  -0.014704   0.056166  27.543398

In [27]:
df.describe()

         Feature 1    Feature 2       Target
count  1000.000000  1000.000000  1000.000000
mean     -0.026581     0.051872     0.700044
std       1.031955     0.982415    64.093182
min      -3.086989    -3.051894  -181.496246
25%      -0.745907    -0.631354   -42.998355
50%      -0.037282     0.024534     1.219142
75%       0.656433     0.684512    46.886805
max       3.191106     3.237773   227.420424

In [29]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')
fig.show()

ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of ['Feature 1', 'Feature 2', 'Target'] but received: feature1