In [39]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [40]:
X, Y = make_regression(n_samples=1000, n_features= 2, n_informative=2, n_targets=1, noise =50)

In [41]:
df = pd.DataFrame({'Feature 1':X[:,0], 'Feature 2':X[:,1], 'Target':Y})

In [42]:
df.head()

   Feature 1  Feature 2     Target
0  -0.489203   0.067056  23.980945
1  -0.372949  -1.091250  -0.830983
2  -0.901430  -1.091804  69.654680
3   1.882391   0.025170  76.053102
4   0.232991   0.672151  15.852664

In [43]:
df.describe()

         Feature 1    Feature 2       Target
count  1000.000000  1000.000000  1000.000000
mean     -0.000653     0.021178     0.429156
std       1.001467     0.994954    58.098234
min      -2.902451    -3.844217  -145.000134
25%      -0.648907    -0.637019   -39.566003
50%      -0.029839    -0.001652    -2.476744
75%       0.689888     0.642220    40.286899
max       3.166333     3.664617   212.358706

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train,Y_test = train_test_split(X,Y, test_size =0.2, random_state=3)

In [46]:
from sklearn.linear_model import LinearRegression

In [47]:
lr = LinearRegression().fit(X_train, Y_train)

In [48]:
y_pred = lr.predict(X_test)

In [49]:
mean_absolute_error(Y_test,y_pred)

43.244363774200025

In [50]:
mean_squared_error(Y_test,y_pred)

2810.2118148958393

In [51]:
r2_score(Y_test,y_pred)

0.17195293258281064

In [52]:
lr.coef_

array([12.25761172, 26.43521102])

In [53]:
lr.intercept_

np.float64(-0.09280594313485246)